import { TimelineArtifacts } from "#root/index.js";

/**
 * Unified, provider-agnostic return type for any AI provider call.
 *
 * @template TOutput Type of the main output (e.g., string for chat, number[] for embeddings, image info)
 */
export interface AIResponse<TOutput = unknown> {
    /** The main output of the call, e.g., text, embedding vector, image URL, etc. */
    output: TOutput;

    /** The raw response object returned by the provider; useful for debugging or logging */
    rawResponse?: unknown;

    /** Unique ID for this response, generated by the SDK */
    id?: string;

    /** Multimodal artifacts generated from provider call that should be stored in session */
    multimodalArtifacts?: TimelineArtifacts;
    
    /**
     * Metadata about the request/response.
     * May include model used, provider, request ID, timing, and token usage.
     */
    metadata?: {
        model?: string;
        provider?: string;
        requestId?: string;
        responseTimeMs?: number;
        status?: string;
        timestamp?: number;
        tokensUsed?: number;
        [key: string]: unknown;
    };

    /** Any error information returned by the provider */
    error?: Error | string;
}

/**
 * Represents a single chunk of a streaming response.
 *
 * Used for chat streaming, image generation streaming, etc.
 * Each chunk may contain incremental updates and partial outputs.
 *
 * @template TChunk Type of the output in this chunk
 */
export interface AIResponseChunk<TChunk = unknown> {
    /** Main output of this chunk (may be partial) */
    output?: TChunk;

    /** Incremental update to the output (useful for text streams, embeddings, etc.) */
    delta?: TChunk;

    /** Full raw response for this chunk, if needed for debugging */
    raw?: unknown;

    /** True only for the final chunk of a streaming response */
    done: boolean;

    /** Optional provider request ID for tracing */
    id?: string;

    /** Multimodal artifacts generated from provider call that should be stored in session */
    multimodalArtifacts?: TimelineArtifacts;

    /**
     * Metadata about the request/response for this chunk.
     * Includes model, provider, request ID, timestamp, token usage, etc.
     */
    metadata?: {
        model?: string;
        provider?: string;
        requestId?: string;
        responseTimeMs?: number;
        status?: string;
        timestamp?: number;
        tokensUsed?: number;
        [key: string]: unknown;
    };

    /** Optional error information if this chunk encountered an error */
    error?: Error | string;
}
