import { NormalizedArtifactBase } from "#root/index.js";

/**
 * Normalized representation of any audio output produced by a provider.
 *
 * Examples:
 * - TTS output
 * - Audio responses from multimodal models
 * - Audio generated by tools
 */
export interface NormalizedAudio extends NormalizedArtifactBase {
    /** Audio artifact kind: synthesized speech, transcription source, translated speech, etc. */
    kind?: "tts" | "transcription" | "translation" | "speech" | "other";

    /** MIME type (e.g. audio/mpeg, audio/wav, audio/ogg) */
    mimeType: string;

    /** Public or signed URL to the audio */
    url?: string;

    /** Base64-encoded audio data */
    base64?: string;

    /** Duration in seconds, if known */
    durationSeconds?: number;

    /** Detected or output language code (e.g. "en", "es", "fr"). */
    language?: string;

    /** Transcript if provider returned one */
    transcript?: string;

    /** Start/end-timestamped transcript segments when available from provider. */
    segments?: Array<{
        id?: string;
        startSeconds?: number;
        endSeconds?: number;
        text: string;
        speaker?: string;
    }>;

    /** Word-level timing/confidence data when available. */
    words?: Array<{
        word: string;
        startSeconds?: number;
        endSeconds?: number;
        confidence?: number;
        speaker?: string;
    }>;

    /** Sample rate in Hz when known (e.g. 16000, 44100, 48000). */
    sampleRateHz?: number;

    /** Number of channels when known (1 = mono, 2 = stereo). */
    channels?: number;

    /** Average bitrate in bits per second when known. */
    bitrate?: number;
}
