import { NormalizedArtifactBase } from "#root/index.js";

/**
 * Normalized representation of any audio output produced by a provider.
 *
 * Examples:
 * - TTS output
 * - Audio responses from multimodal models
 * - Audio generated by tools
 */
export interface NormalizedAudio extends NormalizedArtifactBase {
    /** MIME type (e.g. audio/mpeg, audio/wav, audio/ogg) */
    mimeType: string;

    /** Public or signed URL to the audio */
    url?: string;

    /** Base64-encoded audio data */
    base64?: string;

    /** Duration in seconds, if known */
    durationSeconds?: number;

    /** Transcript if provider returned one */
    transcript?: string;
}
